## Adapted from https://medium.com/@jaredhatfield/publishing-semantic-versioned-docker-images-to-github-packages-using-github-actions-ebe88fa74522
## and https://github.com/docker/build-push-action
name: Docker autogenerate and push to DockerHub

on:
  release:
    types: [published]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_USER_PASSWORD }}
      - name: Set up Docker builder
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fabianry/gss:latest, fabianry/gss:${{ github.event.release.tag_name }}
